### ISSUE TITLE
Unable to cast Int64 to Float64

### ISSUE THREAD

**Issue by jwoertink** [NeuraLegion/sec-tester-cr#19]
@mdwagner has been working on some updated specs for Lucky, and started running in to this conversion error. I think it's coming from this line

https://github.com/NeuraLegion/sec-tester-cr/blob/f1d991c645d7683d61f5c6becfdeff86152e04e1/src/sec_tester/scan.cr#L131

Maybe `response_json["elapsed"]` returns `Int64` here? 

For now we're able to work around it with a little hack :joy: 

```
RUN sed -i '131s/as_f/as_i/' lib/sec_tester/src/sec_tester/scan.cr
```

**Comment by bararchy** [comment]
@derevnjuk what does `elapsed` returns in this context? :sweat_smile:

**Comment by bararchy** [comment]
@jwoertink Fixed via: 0d447ffd58c758c2d106008e51bf624fb5ea6779 
I used `as_i64` to make sure it will always parse correctly.
I'll cut a new minor release soon

**Comment by bararchy** [comment]
Closed by: https://github.com/NeuraLegion/sec-tester-cr/releases/tag/v1.6.3

@jwoertink let me know if there is any other issue :pray:

**Comment by mdwagner** [comment]
New build passed! Thanks!

**Comment by jwoertink** [comment]
Thanks @bararchy!
